apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apache-nifi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apache-nifi.labels" . | nindent 4 }}
data:
  {{- if .Values.app.singleUserCredentialsUsername }}
  SINGLE_USER_CREDENTIALS_USERNAME: {{ .Values.app.singleUserCredentialsUsername }}
  {{- end }}
