apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apache-nifi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apache-nifi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.app.singleUserCredentialsPassword }}
  SINGLE_USER_CREDENTIALS_PASSWORD: {{ .Values.app.singleUserCredentialsPassword | quote }}
  {{- end }}