apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-nifi.fullname" . }}
  labels:
    {{- include "apache-nifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    # - port: 80
    #   targetPort: http
    #   protocol: TCP
    #   name: http
  selector:
    {{- include "apache-nifi.selectorLabels" . | nindent 4 }}
