apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  # https://www.keycloak.org/server/all-config
  KC_DB: {{ .Values.persistence.dbType }}
  KC_DB_URL_DATABASE: {{ .Values.persistence.dbName }}
  KC_DB_URL_HOST: postgresql.{{ .Release.Namespace }}.svc.cluster.local
  KC_DB_URL_PORT: "{{ .Values.persistence.dbPort }}"
  KC_DB_USERNAME: {{ .Values.persistence.dbUser }}
  KC_HOSTNAME: {{ .host | quote }}
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.app.bootstrapAdminUsername }}
{{- if .Values.app.proxy }}
  KC_PROXY: {{ .Values.app.proxy }}
{{- end }}