apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolibarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.app.dbPassword }}
  DOLI_ADMIN_PASSWORD: {{ .Values.app.adminPassword | quote }}
  {{- end }}
  {{- if .Values.persistence.dbPassword }}
  DOLI_DB_PASSWORD: {{ .Values.persistence.dbPassword | quote }}
  {{- end }}
  {{- if .Values.app.doliCronKey }}
  DOLI_CRON_KEY: {{ .Values.app.doliCronKey }}
  {{- end }}
